### ISSUE TITLE
Why is this a command line application? 

### ISSUE THREAD

**Issue by dpsanders** [djsegal/julz_legacy#22]
Rather than a Julia script or package?

**Comment by djsegal** [comment]
it probably could be, the truth is:
- I wanted to bang it out in a weekend and get a working prototype
- I found a good [tutorial for building a python cli](https://stormpath.com/blog/building-simple-cli-interfaces-in-python)

**Comment by djsegal** [comment]
I'm rewriting it as a Julia package.

https://github.com/djsegal/Julz.jl
